### ISSUE TITLE
invalid characters in address field

### ISSUE THREAD

**Issue by edoderoo** [VDK/WLM-table-gen-2#1]
an address formatted 's Gravelande did stop the process of finding GEO-locations.
I tried to put the CSV-file in the format "'s Gravelande" but that didn't help
Deleting the ' character form the CSV did help (in my case)

**Comment by VDK** [comment]
[fixed](https://github.com/VDK/WLM-table-gen-2/commit/2e62c2e9752ccdb860c42bec40a4806602de608f#diff-5c1cac51e3d10be5356a868ef460ca51)

**Comment by VDK** [comment]
This is caused by the use of characters such as – and ’ , which look like - and ' but are actually special characters outside the ASCII range. For some reason just S&R them doesn't work just yet.
